version: '3.3'

services:
  app:
    image: weatherviewer
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    build:
      context: .
      dockerfile: Dockerfile
    ports: 
      - "80:80"
    networks:
      - backend
    depends_on: 
      - postgres_db
      - redis
      
  postgres_db:
    container_name: postgres
    image: postgres:latest
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    networks: 
      - backend
    volumes:
      - postgres-data:/var/lib/postgresql/data
    
  redis:
    image: redis:alpine
    ports:
      - "5002:5002"
    networks: 
      - backend

volumes: 
  postgres-data: 
    
networks:
  backend:
    driver: bridge